import { defineEnemies } from "./define";

/** Adding an enemy is adding an entry here (ADR 008). Each one asks a different question of the defense. */
export const ENEMIES = defineEnemies({
  normal: {
    label: "Laburante",
    line: "camina y ya",
    armor: "none",
    hp: 55,
    speed: 50,
    bounty: 8,
    livesCost: 1,
    wallDamage: 2,
    color: 0xe05252,
    radius: 0.28,
  },
  swarm: {
    label: "Mosquitos",
    line: "muchos y chiquitos",
    armor: "none",
    hp: 18,
    speed: 65,
    bounty: 2,
    livesCost: 1,
    wallDamage: 1,
    color: 0xd98c8c,
    radius: 0.16,
  },
  fast: {
    label: "Motoquero",
    line: "pasa rápido, armadura ligera",
    armor: "light",
    hp: 32,
    speed: 100,
    bounty: 8,
    livesCost: 1,
    wallDamage: 2,
    color: 0xf4c542,
    radius: 0.2,
  },
  rider: {
    label: "Ciclista",
    line: "ligero y aguanta",
    armor: "light",
    hp: 130,
    speed: 45,
    bounty: 14,
    livesCost: 1,
    wallDamage: 4,
    color: 0x8fa3b8,
    radius: 0.3,
  },
  tank: {
    label: "Camión",
    line: "lento, pesado, cuesta dos vidas",
    armor: "heavy",
    hp: 320,
    speed: 30,
    bounty: 30,
    livesCost: 2,
    wallDamage: 8,
    color: 0x9c2f2f,
    radius: 0.38,
  },
  enchanted: {
    label: "Aparecido",
    line: "encantado",
    armor: "enchanted",
    hp: 80,
    speed: 55,
    bounty: 12,
    livesCost: 1,
    wallDamage: 2,
    color: 0xb07cf0,
    radius: 0.26,
  },
  shade: {
    label: "Colado",
    line: "no se ve sin Chusma",
    armor: "none",
    hp: 60,
    speed: 60,
    bounty: 10,
    livesCost: 1,
    wallDamage: 2,
    color: 0x6e6e8a,
    radius: 0.24,
    stealth: true,
  },
  healer: {
    label: "Curandero",
    line: "cura a los de al lado",
    armor: "enchanted",
    hp: 90,
    speed: 45,
    bounty: 14,
    livesCost: 1,
    wallDamage: 1,
    color: 0x7fe0a0,
    radius: 0.26,
    heal: { amount: 5, range: 1500, every: 10 },
  },
  shielded: {
    label: "Patovica",
    line: "el primer golpe no le entra",
    armor: "heavy",
    hp: 150,
    speed: 45,
    bounty: 16,
    livesCost: 1,
    wallDamage: 6,
    color: 0xc8d8e8,
    radius: 0.3,
    shieldHits: 1,
  },
  blob: {
    label: "Ñoqui",
    line: "al morir se parte en tres",
    armor: "none",
    hp: 120,
    speed: 40,
    bounty: 10,
    livesCost: 1,
    wallDamage: 3,
    color: 0x9be05a,
    radius: 0.32,
    split: { kind: "blobling", count: 3 },
  },
  blobling: {
    label: "Ñoquito",
    line: "lo que queda de un Ñoqui",
    armor: "none",
    hp: 30,
    speed: 55,
    bounty: 3,
    livesCost: 1,
    wallDamage: 1,
    color: 0xb8f07a,
    radius: 0.18,
  },
  boss: {
    label: "Patrón",
    line: "cinco vidas, viene con algo",
    armor: "heavy",
    hp: 600,
    speed: 35,
    bounty: 100,
    livesCost: 5,
    wallDamage: 20,
    color: 0xff5c5c,
    radius: 0.45,
  },
});

export type EnemyKind = keyof typeof ENEMIES;

export const ENEMY_KINDS = Object.keys(ENEMIES) as EnemyKind[];

export type { EnemyDef, EnemySpec } from "./define";
